<?php

namespace TS\ContactBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function getNumberContact($id){
        return $this->_em
                ->createQuery('SELECT COUNT(t) FROM TSContactBundle:Contact t
                        WHERE t.user = :user')
                ->setParameter('user',$id)
                ->getSingleScalarResult();
    }
    
    public function getHommeContact($id){
        return $this->_em
                ->createQuery('SELECT COUNT(t) FROM TSContactBundle:Contact t
                        WHERE t.user = :user and t.sexe = :sexe')
                ->setParameter('user',$id)
                ->setParameter('sexe','Homme')
                ->getSingleScalarResult();
    }
    
    public function getFemmeContact($id){
        return $this->_em
                ->createQuery('SELECT COUNT(t) FROM TSContactBundle:Contact t
                        WHERE t.user = :user and t.sexe = :sexe')
                ->setParameter('user',$id)
                ->setParameter('sexe','Femme')
                ->getSingleScalarResult();
    }
}
